name: help_ukraine_widget
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_sfsymbols: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  solid_lints: ^0.0.12

flutter:
  uses-material-design: true

  fonts:
    - family: sficonsets
      fonts:
        - asset: packages/flutter_sfsymbols/fonts/sficonsets.ttf
